version: '3.9'

services:
  frontend:
    restart: always
    build:
      context: .
    command: ['npm', 'run', 'start']
    volumes:
      - .:/app/
    ports:
      - '${APP_PORT:-4000}:${APP_PORT:-4000}'
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - frontend
