export enum Prices {
  MONTHLY = 20,
  YEARLY = 15,
}

export enum SubsPriceIdStripe {
  STARTER_MONTHLY_PROD = 'price_1LlwmfLPHXTxUZlW2Wi6aaDj',
  STARTER_YEARLY_PROD = 'price_1LlwmfLPHXTxUZlWy3aWFEBg',
  PRO_MONTHLY_PROD = 'price_1Llwo8LPHXTxUZlWehIWEUe9',
  PRO_YEARLY_PROD = 'price_1Llwo8LPHXTxUZlWEJSuhGwC',

  STARTER_MONTHLY_DEV = 'price_1LlzjoLPHXTxUZlWZDHARD8E',
  STARTER_YEARLY_DEV = 'price_1LlzjoLPHXTxUZlWJkiYgVa9',
  PRO_MONTHLY_DEV = 'price_1LlzkPLPHXTxUZlW4d7m0DRm',
  PRO_YEARLY_DEV = 'price_1LlzkPLPHXTxUZlWLYur9mAV',

  STARTER_DOWNSELL_MONTHLY_DEV = 'price_1Llzl7LPHXTxUZlWw3OAYOzF',
  STARTER_DOWNSELL_YEARLY_DEV = 'price_1Llzl7LPHXTxUZlWnGkSNIKj',
  PRO_DOWNSELL_MONTHLY_DEV = 'price_1LlzllLPHXTxUZlWNfdpE34D',
  PRO_DOWNSELL_YEARLY_DEV = 'price_1LlzllLPHXTxUZlWolK3GMfY',

  STARTER_DOWNSELL_MONTHLY_PROD = 'price_1LlzeRLPHXTxUZlWagjs8SUT',
  STARTER_DOWNSELL_YEARLY_PROD = 'price_1LlzeRLPHXTxUZlWZnRi1ctk',
  PRO_DOWNSELL_MONTHLY_PROD = 'price_1LlzflLPHXTxUZlWww9G1HyE',
  PRO_DOWNSELL_YEARLY_PROD = 'price_1LlzflLPHXTxUZlWVX5uVS7k',
}

export enum StripeProductKeys {
  POTATO_PRO_DEV = 'prod_MUzjT8yaV9ecJ0',
  POTATO_STARTER_DEV = 'prod_MUzjngoXbsXCyg',
  POTATO_PRO_PROD = 'prod_MUwh5WNiYRyeIH',
  POTATO_STARTER_PROD = 'prod_MUwgCl8NIcuufA',
}
