export enum LinkList {
  Landing = '/',
  Pricing = '/pricing',
  Checkout = '/checkout',
  AddToCard = '/add-to-card',
  Success = '/success',
  About = '/about',
  Faq = '/faq',
  Demo = '/demo',
  Login = '/login',
  TermsAndConditions = '/t&c',
  PrivacyPolicy = '/privacy-policy',
  Membership = '/membership',

  WAITLIST = '/waitlist',
  DASHBOARD = '/dashboard',
  TRENDS = '/trends',
  DISCOVER = '/discover',
  FORYOU = '/foryou',
  PROFILE = '/profile',
}