export enum LinkList {
  Home = '/',
  Landing = '/landing',
  Quiz = '/quiz',
  Email = '/email',
  Pricing = '/pricing',
  Checkout = '/checkout',
  QuizCheckout = '/quiz-checkout',
  AddToCard = '/add-to-card',
  Success = '/success',
  About = '/about',
  Faq = '/faq',
  Demo = '/demo',
  Login = '/login',
  ResetPassword = '/reset-password',
  ResetPasswordCode = '/reset-password-code',
  Register = '/register',
  TermsAndConditions = '/t&c',
  PrivacyPolicy = '/privacy-policy',
  Membership = '/membership',

  // private routes
  WAITLIST = '/waitlist',
  DASHBOARD = '/dashboard',
  TRENDS = '/trends',
  DISCOVER = '/discover',
  INFLUENCERS = '/influencers',
  FORYOU = '/foryou',
  PROFILE = '/profile',
  FUNDS = '/funds',
  EXPIRED_SUBSCRIPTION = '/expired-subscription',
  YOUR_INFLUENCERS = '/your-influencers',
  SUGGESTIONS = '/suggestions',
  PARTNERSHIPS = '/partnerships',
}
